
name: Merge master into develop

on:
  pull_request:
    branches: [master]
    types: [closed]

# permissions:
#   contents: write

jobs:
  merge-master-back-to-develop:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Merge master back to develop
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "Github Actions"
        git fetch --unshallow
        git checkout develop
        git pull
        git merge --no-ff origin/master -m "Auto-merge master back to develop"
        git push
